/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fx_calc;

import java.text.DecimalFormat;

/**
 *
 * @author Emmynem
 */
public class Gold_Silver_SLTP_Calc extends javax.swing.JFrame {

    /**
     * Creates new form XAUUSD_SLTP_Calc
     */
    public Gold_Silver_SLTP_Calc() {
        initComponents();
    }

    public void Calculate() {
        RawSLTPCalc RSLTP = new RawSLTPCalc();
        DecimalFormat df = new DecimalFormat("#.##");

        String PriceText = EnterPriceTextField.getText();
        String SlText = EnterSLTextField.getText();
        String TPText = EnterTPTextField.getText();

        try {
            int slPips = Integer.parseInt(SlText);
            int tpPips = Integer.parseInt(TPText);
            double Price = Double.parseDouble(PriceText);
            int len = PriceText.length();
            RSLTP.setPrice(Price);
            RSLTP.setSL_Pips(slPips);
            RSLTP.setTP_Pips(tpPips);
            if (len > 7) {
                ErrorLabel.setText("Price must be point(.) 2 decimals i.e (0.00)");
                SlLabel.setText(null);
                TpLabel.setText(null);
            } else {
                switch (TradeOptionJComboBox.getSelectedIndex()) {
                    case 1:
                        double Buy_SL_Result = RSLTP.Gold_Silver_Buy_SL_pips_Value();
                        String str_Buy_SL_Result = df.format(Buy_SL_Result);

                        double Buy_TP_Result = RSLTP.Gold_Silver_Buy_TP_pips_Value();
                        String str_Buy_TP_Result = df.format(Buy_TP_Result);

                        SlLabel.setText("SL = " + str_Buy_SL_Result);
                        TpLabel.setText("TP = " + str_Buy_TP_Result);
                        ErrorLabel.setText(null);
                        break;

                    case 2:
                        double Sell_SL_Result = RSLTP.Gold_Silver_Sell_SL_pips_Value();
                        String str_Sell_SL_Result = df.format(Sell_SL_Result);

                        double Sell_TP_Result = RSLTP.Gold_Silver_Sell_TP_pips_Value();
                        String str_Sell_TP_Result = df.format(Sell_TP_Result);

                        SlLabel.setText("SL = " + str_Sell_SL_Result);
                        TpLabel.setText("TP = " + str_Sell_TP_Result);
                        ErrorLabel.setText(null);
                        break;

                    default:
                        ErrorLabel.setText("Choose Either Buy or Sell");
                        SlLabel.setText(null);
                        TpLabel.setText(null);
                        break;
                }

            }

        } catch (NumberFormatException e) {
            ErrorLabel.setText("Wrong Input, Must be decimal numbers.");
            SlLabel.setText(null);
            TpLabel.setText(null);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        GoldSilverLabel = new javax.swing.JLabel();
        EnterSLLabel = new javax.swing.JLabel();
        EnterSLTextField = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        SlLabel = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        EnterTPLabel = new javax.swing.JLabel();
        EnterTPTextField = new javax.swing.JTextField();
        EnterPriceLabel = new javax.swing.JLabel();
        EnterPriceTextField = new javax.swing.JTextField();
        TpLabel = new javax.swing.JLabel();
        SLTPCalcLabel = new javax.swing.JLabel();
        TradeOptionJComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gold / Silver - SL /  TP Pairs");
        setMaximumSize(new java.awt.Dimension(700, 540));
        setMinimumSize(new java.awt.Dimension(700, 540));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));
        MainPanel.setMaximumSize(new java.awt.Dimension(700, 540));
        MainPanel.setMinimumSize(new java.awt.Dimension(700, 540));

        GoldSilverLabel.setFont(new java.awt.Font("BEYNO", 0, 24)); // NOI18N
        GoldSilverLabel.setForeground(new java.awt.Color(204, 0, 0));
        GoldSilverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GoldSilverLabel.setText("Gold /Silver");
        GoldSilverLabel.setToolTipText("Stop Loss / Take Profit Calculator");
        GoldSilverLabel.setPreferredSize(new java.awt.Dimension(100, 19));

        EnterSLLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        EnterSLLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterSLLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnterSLLabel.setText("Enter Stop Loss Pips");

        CalculateButton.setBackground(new java.awt.Color(0, 153, 153));
        CalculateButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(204, 255, 204));
        CalculateButton.setText("Calculate");
        CalculateButton.setToolTipText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        SlLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        SlLabel.setForeground(new java.awt.Color(204, 255, 204));
        SlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ErrorLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(204, 0, 51));
        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BackButton.setBackground(new java.awt.Color(255, 51, 0));
        BackButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 255, 204));
        BackButton.setText("<<< Back");
        BackButton.setToolTipText("Go back to last page .");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(255, 0, 0));
        ResetButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(204, 255, 204));
        ResetButton.setText("Reset");
        ResetButton.setToolTipText("Reset Values");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        EnterTPLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        EnterTPLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterTPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnterTPLabel.setText("Enter Take Profit Pips");

        EnterPriceLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        EnterPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnterPriceLabel.setText("Enter Price");

        TpLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        TpLabel.setForeground(new java.awt.Color(204, 255, 204));
        TpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        SLTPCalcLabel.setFont(new java.awt.Font("BEYNO", 0, 24)); // NOI18N
        SLTPCalcLabel.setForeground(new java.awt.Color(204, 0, 0));
        SLTPCalcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLTPCalcLabel.setText("SL /TP Calculation");
        SLTPCalcLabel.setToolTipText("Pips Calculator");
        SLTPCalcLabel.setPreferredSize(new java.awt.Dimension(100, 19));

        TradeOptionJComboBox.setBackground(new java.awt.Color(204, 204, 204));
        TradeOptionJComboBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        TradeOptionJComboBox.setForeground(new java.awt.Color(204, 255, 204));
        TradeOptionJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trade option", "Buy", "Sell" }));
        TradeOptionJComboBox.setToolTipText("Choose whether to BUY or SELL");
        TradeOptionJComboBox.setMaximumSize(new java.awt.Dimension(32767, 35));
        TradeOptionJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TradeOptionJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SLTPCalcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(GoldSilverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(TradeOptionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(SlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(365, 365, 365))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EnterSLTextField)
                                    .addComponent(EnterSLLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EnterPriceTextField)
                                    .addComponent(EnterPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EnterTPTextField)
                                    .addComponent(EnterTPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(GoldSilverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SLTPCalcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(EnterTPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnterTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(EnterPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnterPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(EnterSLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnterSLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TradeOptionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SLTPCalc().setVisible(true);
            }
        });
    }//GEN-LAST:event_BackButtonActionPerformed

    private void TradeOptionJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TradeOptionJComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TradeOptionJComboBoxActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        ErrorLabel.setText(null);
        SlLabel.setText(null);
        TpLabel.setText(null);
        EnterPriceTextField.setText(null);
        EnterSLTextField.setText(null);
        EnterTPTextField.setText(null);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
        Calculate();
    }//GEN-LAST:event_CalculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gold_Silver_SLTP_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gold_Silver_SLTP_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gold_Silver_SLTP_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gold_Silver_SLTP_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gold_Silver_SLTP_Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel EnterPriceLabel;
    private javax.swing.JTextField EnterPriceTextField;
    private javax.swing.JLabel EnterSLLabel;
    private javax.swing.JTextField EnterSLTextField;
    private javax.swing.JLabel EnterTPLabel;
    private javax.swing.JTextField EnterTPTextField;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JLabel GoldSilverLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SLTPCalcLabel;
    private javax.swing.JLabel SlLabel;
    private javax.swing.JLabel TpLabel;
    private javax.swing.JComboBox<String> TradeOptionJComboBox;
    // End of variables declaration//GEN-END:variables
}
